import json
import os

from dotenv import load_dotenv

load_dotenv()

DISCORD_BOT_TOKEN = os.getenv('DISCORD_TOKEN')

LINE_NOTIFY_REDIRECT_URL = os.getenv('LINE_NOTIFY_REDIRECT_URL')
LINE_NOTIFY_CLIENT_ID = os.getenv('LINE_NOTIFY_CLIENT_ID')
LINE_NOTIFY_CLIENT_SECRET = os.getenv('LINE_NOTIFY_CLIENT_SECRET')

GOOGLE_SPREADSHEET_SHEET_KEY = os.getenv('GOOGLE_SPREADSHEET_SHEET_KEY')
GOOGLE_SPREADSHEET_SERVICE_ACCOUNT = json.loads(os.getenv('GOOGLE_SPREADSHEET_SERVICE_ACCOUNT'))

NOTIFY_API_KEY = os.getenv('NOTIFY_API_KEY')

PORT = int(os.getenv('PORT', 8080))
